### Post Request Example

In [40]:
import requests as r
import json

POST_JSON = {
    'input_city': 'Los Angeles AP, California',
    'input_tank': [12, 8, 9],
    'input_contents': [8450, 'other stocks', 11.5, 4.5],
    'input_chem': ['Cyclohexane', 'Benzene', 'Toluene'],
    'input_qty': [101, 2812, 258],
    'input_default': [0.0625, 1],
    'input_condition': ['White', 'None', 'Average'],
    'input_tank_type': 'Vertical',
    'input_tank_name': 'Tank 100019',
    'input_facility_name': 'Marathon Refinery Carson',
    'input_facility_address': '2101 Pacific Coast Hwy, Wilmington, CA 90744',
    'input_tank_geo': [33.793548, -118.233320]
}

r.post('http://127.0.0.1:5000/api/vfrtk', json=POST_JSON).json()

{'detail': {'0': {'antoine_coef_a': '6.841',
   'antoine_coef_b': '1201.53',
   'antoine_coef_c': '222.65',
   'cas_no': '00110-82-7',
   'comp_amt': 101,
   'comp_mole': 1.2000950570342208,
   'comp_mole_xi': 0.030001627954575505,
   'comp_partial': 0.04228188501161753,
   'comp_partial_tln': 0.037409220222619034,
   'comp_partial_tlx': 0.04766699905006402,
   'comp_vap_mole_frac': 0.032601043057804445,
   'comp_vapor_mw_xi': 2.7437037837448215,
   'comp_vp': 1.4093196901059892,
   'comp_vp_tln': 1.2469063438577108,
   'comp_vp_tlx': 1.588813751114942,
   'component': 'Cyclohexane',
   'facility_name': 'Marathon Refinery Carson',
   'mw': '84.15999999999998',
   'stand_loss_xi': 2.55037487580329,
   'tank_name': 'Tank 100019',
   'tank_type': 'Vertical',
   'total_loss_xi': 3.2616258015873094,
   'vap_mole_xi': 274.37037837448213,
   'vap_wt_xi': 0.03490515559331356,
   'work_loss_xi': 0.7112509257840197},
  '1': {'antoine_coef_a': '6.905',
   'antoine_coef_b': '1211.033',
   'antoine_coef_c': '220.79',
   'cas_no': '00071-43-2',
   'comp_amt': 2812,
   'comp_mole': 36.00051209832288,
   'comp_mole_xi': 0.8999903497788334,
   'comp_partial': 1.2271640443049532,
   'comp_partial_tln': 1.082595221532725,
   'comp_partial_tlx': 1.3873684128348156,
   'comp_vap_mole_frac': 0.9461930998673023,
   'comp_vapor_mw_xi': 73.90714303063498,
   'comp_vp': 1.3635302251924373,
   'comp_vp_tln': 1.2028964774997482,
   'comp_vp_tlx': 1.5415369877863159,
   'component': 'Benzene',
   'facility_name': 'Marathon Refinery Carson',
   'mw': '78.11',
   'stand_loss_xi': 68.69944264554118,
   'tank_name': 'Tank 100019',
   'tank_type': 'Vertical',
   'total_loss_xi': 87.85840733189816,
   'vap_mole_xi': 7390.714303063498,
   'vap_wt_xi': 0.9402401025305154,
   'work_loss_xi': 19.158964686356992},
  '2': {'antoine_coef_a': '6.954',
   'antoine_coef_b': '1344.8',
   'antoine_coef_c': '219.48',
   'cas_no': '00108-88-3',
   'comp_amt': 258,
   'comp_mole': 2.8003907521979814,
   'comp_mole_xi': 0.07000802226659113,
   'comp_partial': 0.027502911757260082,
   'comp_partial_tln': 0.023892350203901194,
   'comp_partial_tlx': 0.031564816736462324,
   'comp_vap_mole_frac': 0.02120585707489324,
   'comp_vapor_mw_xi': 1.953695612309914,
   'comp_vp': 0.39285371685731624,
   'comp_vp_tln': 0.3412801766191727,
   'comp_vp_tlx': 0.45087428146824715,
   'component': 'Toluene',
   'facility_name': 'Marathon Refinery Carson',
   'mw': '92.13',
   'stand_loss_xi': 1.816032850966736,
   'tank_name': 'Tank 100019',
   'tank_type': 'Vertical',
   'total_loss_xi': 2.3224897874582595,
   'vap_mole_xi': 195.3695612309914,
   'vap_wt_xi': 0.024854741876171114,
   'work_loss_xi': 0.5064569364915235}},
 'summary': {'standing_losses': {'Tank 100019': 73.0658503723112},
  'total_losses': {'Tank 100019': 93.44252292094373},
  'working_losses': {'Tank 100019': 20.376672548632534}}}

In [1]:
import pandas as pd

df = pd.read_csv('met_db.csv')

In [2]:
df['lat'] = ''
df['lon'] = ''

In [3]:
import folium
import requests as r
import json

def geocoder_conn_str(input_addr):

    QUERY = '%20'.join(input_addr.split(' '))
    BASE = 'https://us1.locationiq.com/v1/search.php?key='

    conn_str = BASE + 'eeb5b8923de08c' + '&q=' + QUERY + '&format=json'

    data = r.get(conn_str).json()

    return [float(data[0]['lat']), float(data[0]['lon'])]

In [5]:
except_list = []

for index, row in df.iterrows():
    try:
        data = geocoder_conn_str(row['CTYST'])
        df.set_value(index, 'lat', data[0])
        df.set_value(index, 'lon', data[1])
        print('Completed Index: {} & City: {}'.format(index, row['CTYST']))
    except:
        except_list.append(index)
        print('Error: {} & City: {}'.format(index, row['CTYST']))
except_list

Error: 0 & City: Cape Hatteras, North Carolina
Error: 1 & City: Caribou, Maine
Error: 2 & City: Casper, Wyoming
Error: 3 & City: Charleston AP, South Carolina
Error: 4 & City: Beckley, West Virginia
Error: 5 & City: Bethel, Alaska
Error: 6 & City: Bettles, Alaska
Error: 7 & City: Big Delta, Alaska
Error: 8 & City: Billings, Montana
Error: 9 & City: Binghamton, New York
Error: 10 & City: Birmingham AP, Alabama
Error: 11 & City: Bishop, California
Error: 12 & City: Aberdeen, South Dakota
Error: 13 & City: Abilene, Texas
Error: 14 & City: Akron, Ohio
Error: 15 & City: Alamosa, Colorado
Error: 16 & City: Albany, New York
Error: 17 & City: Albuquerque, New Mexico
Error: 18 & City: Allentown, Pennsylvania
Error: 19 & City: Alpena, Michigan
Error: 20 & City: Amarillo, Texas
Error: 21 & City: Anchorage, Alaska
Error: 22 & City: Annette, Alaska
Error: 23 & City: Apalachicola, Florida
Error: 24 & City: Asheville, North Carolina
Error: 25 & City: Astoria, Oregon
Error: 26 & City: Athens, Georgia
Error: 27 & City: Atlanta, Georgia
Error: 28 & City: Atlantic City AP, New Jersey
Error: 29 & City: Atlantic City C.O., New Jersey
Error: 30 & City: Augusta, Georgia
Error: 31 & City: Austin, Texas
Error: 32 & City: Bakersfield, California
Error: 33 & City: Baltimore, Maryland
Error: 34 & City: Barrow, Alaska
Error: 35 & City: Baton Rouge, Louisiana
Error: 36 & City: Bismarck, North Dakota
Error: 37 & City: Boise, Idaho
Error: 38 & City: Boston, Massachusetts
Error: 39 & City: Bridgeport, Connecticut
Error: 40 & City: Bristol-Johnson City, Tennessee
Error: 41 & City: Brownsville, Texas
Error: 42 & City: Buffalo, New York
Error: 43 & City: Burlington, Vermont
Error: 44 & City: Charleston C.O., South Carolina
Error: 45 & City: Charleston, West Virginia
Error: 46 & City: Charlotte, North Carolina
Error: 47 & City: Chattanooga, Tennessee
Error: 48 & City: Cheyenne, Wyoming
Error: 49 & City: Chicago, Illinois
Error: 50 & City: Clayton, New Mexico
Error: 51 & City: Cleveland, Ohio
Error: 52 & City: Cold Bay, Alaska
Error: 53 & City: Colorado Springs, Colorado
Error: 54 & City: Columbia, Missouri
Error: 55 & City: Columbia, South Carolina
Error: 56 & City: Columbus, Georgia
Error: 57 & City: Columbus, Ohio
Error: 58 & City: Concord, New Hampshire
Error: 59 & City: Concordia, Kansas
Error: 60 & City: Corpus Christi, Texas
Error: 61 & City: Dallas-Fort Worth, Texas
Error: 62 & City: Dayton, Ohio
Error: 63 & City: Daytona Beach, Florida
Error: 64 & City: Del Rio, Texas
Error: 65 & City: Denver, Colorado
Error: 66 & City: Des Moines, Iowa
Error: 67 & City: Detroit, Michigan
Error: 68 & City: Dodge City, Kansas
Error: 69 & City: Dubuque, Iowa
Error: 70 & City: Duluth, Minnesota
Error: 71 & City: El Paso, Texas
Error: 72 & City: Elkins, West Virginia
Error: 73 & City: Elko, Nevada
Error: 74 & City: Ely, Nevada
Error: 75 & City: Erie, Pennsylvania
Error: 76 & City: Eugene, Oregon
Error: 77 & City: Eureka, California
Error: 78 & City: Evansville, Indiana
Error: 79 & City: Fairbanks, Alaska
Error: 80 & City: Fargo, North Dakota
Error: 81 & City: Flagstaff, Arizona
Error: 82 & City: Flint, Michigan
Error: 83 & City: Fort Myers, Florida
Error: 84 & City: Fort Smith, Arkansas
Error: 85 & City: Fort Wayne, Indiana
Error: 86 & City: Fresno, California
Error: 87 & City: Gainesville, Florida
Error: 88 & City: Galveston, Texas
Error: 89 & City: Glasgow, Montana
Error: 90 & City: Goodland, Kansas
Error: 91 & City: Grand Island, Nebraska
Error: 92 & City: Grand Junction, Colorado
Error: 93 & City: Grand Rapids, Michigan
Error: 94 & City: Great Falls, Montana
Error: 95 & City: Green Bay, Wisconsin
Error: 96 & City: Greensboro, North Carolina
Error: 97 & City: Greenville-S'burg, South Carolina
Error: 98 & City: Gulkana, Alaska
Error: 99 & City: Harrisburg, Pennsylvania
Error: 100 & City: Hartford, Connecticut
Error: 101 & City: Helena, Montana
Error: 102 & City: Hilo, Hawaii
Error: 103 & City: Homer, Alaska
Error: 104 & City: Honolulu, Hawaii

/Users/gta/anaconda3/envs/azuredev/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

/Users/gta/anaconda3/envs/azuredev/lib/python3.6/site-packages/ipykernel_launcher.py:7: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  import sys

Completed Index: 105 & City: Houghton Lake, Michigan
Completed Index: 106 & City: Houston, Texas
Error: 107 & City: Huntington, West Virginia
Error: 108 & City: Huntsville, Alabama
Completed Index: 109 & City: Huron, South Dakota
Completed Index: 110 & City: Indianapolis, Indiana
Error: 111 & City: International Falls, Minnesota
Error: 112 & City: Jackson, Kentucky
Error: 113 & City: Jackson, Mississippi
Completed Index: 114 & City: Jacksonville, Florida
Completed Index: 115 & City: Juneau, Alaska
Completed Index: 116 & City: Kahului, Hawaii
Error: 117 & City: Kalispell, Montana
Completed Index: 118 & City: Kansas City, Missouri
Completed Index: 119 & City: Key West, Florida
Error: 120 & City: King Salmon, Alaska
Error: 121 & City: Knoxville, Tennessee
Completed Index: 122 & City: Kodiak, Alaska
Completed Index: 123 & City: Kotzebue, Alaska
Error: 124 & City: La Crosse, Wisconsin
Error: 125 & City: Lake Charles, Louisiana
Error: 126 & City: Lander, Wyoming
Error: 127 & City: Lansing, Michigan
Completed Index: 128 & City: Las Vegas, Nevada
Completed Index: 129 & City: Lewiston, Idaho
Error: 130 & City: Lexington, Kentucky
Error: 131 & City: Lihue, Hawaii
Completed Index: 132 & City: Lincoln, Nebraska
Completed Index: 133 & City: Little Rock, Arkansas
Error: 134 & City: Long Beach, California
Error: 135 & City: Los Angeles AP, California
Error: 136 & City: Los Angeles C.O., California
Completed Index: 137 & City: Louisville, Kentucky
Completed Index: 138 & City: Lubbock, Texas
Error: 139 & City: Lynchburg, Virginia
Error: 140 & City: Macon, Georgia
Error: 141 & City: Madison, Wisconsin
Completed Index: 142 & City: Mansfield, Ohio
Completed Index: 143 & City: Mcgrath, Alaska
Error: 144 & City: Medford, Oregon
Error: 145 & City: Memphis, Tennessee
Error: 146 & City: Meridian, Mississippi
Completed Index: 147 & City: Miami, Florida
Completed Index: 148 & City: Midland-Odessa, Texas
Error: 149 & City: Milford, Utah
Error: 150 & City: Milwaukee, Wisconsin
Error: 151 & City: Minneapolis-St.Paul, Minnesota
Completed Index: 152 & City: Missoula, Montana
Completed Index: 153 & City: Mobile, Alabama
Error: 154 & City: Moline, Illinois
Error: 155 & City: Montgomery, Alabama
Completed Index: 156 & City: Mount Shasta, California
Completed Index: 157 & City: Muskegon, Michigan
Error: 158 & City: Nashville, Tennessee
Error: 159 & City: New Orleans, Louisiana
Error: 160 & City: New York City, New York
Completed Index: 161 & City: Newark, New Jersey
Completed Index: 162 & City: Nome, Alaska
Error: 163 & City: Norfolk, Nebraska
Error: 164 & City: Norfolk, Virginia
Completed Index: 165 & City: North Little Rock, Arkansas
Completed Index: 166 & City: North Platte, Nebraska
Error: 167 & City: Oak Ridge, Tennessee
Error: 168 & City: Oklahoma City, Oklahoma
Error: 169 & City: Olympia, Washington
Completed Index: 170 & City: Omaha (North), Nebraska
Completed Index: 171 & City: Omaha Epply AP, Nebraska
Error: 172 & City: Orlando, Florida
Error: 173 & City: Paducah, Kentucky
Error: 174 & City: Pendleton, Oregon
Completed Index: 175 & City: Pensacola, Florida
Completed Index: 176 & City: Peoria, Illinois
Error: 177 & City: Philadelphia, Pennsylvania
Error: 178 & City: Phoenix, Arizona
Completed Index: 179 & City: Pittsburgh, Pennsylvania
Completed Index: 180 & City: Pocatello, Idaho
Error: 181 & City: Port Arthur, Texas
Error: 182 & City: Portland, Maine
Error: 183 & City: Portland, Oregon
Completed Index: 184 & City: Providence, Rhode Island
Completed Index: 185 & City: Pueblo, Colorado
Error: 186 & City: Quillayute, Washington
Error: 187 & City: Raleigh, North Carolina
Error: 188 & City: Rapid City, South Dakota
Completed Index: 189 & City: Redding, California
Completed Index: 190 & City: Reno, Nevada
Completed Index: 191 & City: Richmond, Virginia
Completed Index: 192 & City: Roanoke, Virginia
Error: 193 & City: Rochester, Minnesota
Error: 194 & City: Rochester, New York
Completed Index: 195 & City: Rockford, Illinois
Completed Index: 196 & City: Roswell, New Mexico
Error: 197 & City: Sacramento, California
Error: 198 & City: Salem, Oregon
Error: 199 & City: Salt Lake City, Utah
Completed Index: 200 & City: San Angelo, Texas
Completed Index: 201 & City: San Antonio, Texas
Error: 202 & City: San Diego, California
Error: 203 & City: San Francisco AP, California
Completed Index: 204 & City: San Francisco C.O., California
Completed Index: 205 & City: Santa Barbara, California
Completed Index: 206 & City: Santa Maria, California
Completed Index: 207 & City: Sault St. Marie, Michigan
Error: 208 & City: Savannah, Georgia
Completed Index: 209 & City: Scotts Bluff, Nebraska
Completed Index: 210 & City: Seattle C.O., Washington
Error: 211 & City: Seattle-TAC AP, Washington
Error: 212 & City: Sheridan, Wyoming
Error: 213 & City: Shreveport, Louisiana
Completed Index: 214 & City: Sioux City, Iowa
Completed Index: 215 & City: Sioux Falls, South Dakota
Error: 216 & City: South Bend, Indiana
Error: 217 & City: Spokane, Washington
Error: 218 & City: Springfield, Illinois
Completed Index: 219 & City: Springfield, Missouri
Completed Index: 220 & City: St. Cloud, Minnesota
Error: 221 & City: St. Louis, Missouri
Error: 222 & City: St. Paul Island, Alaska
Error: 223 & City: Stockton, California
Completed Index: 224 & City: Syracuse, New York
Completed Index: 225 & City: Talkeetna, Alaska
Error: 226 & City: Tallahassee, Florida
Error: 227 & City: Tampa, Florida
Completed Index: 228 & City: Toledo, Ohio
Completed Index: 229 & City: Topeka, Kansas
Error: 230 & City: Tucson, Arizona
Error: 231 & City: Tulsa, Oklahoma
Completed Index: 232 & City: Tupelo, Mississippi
Error: 233 & City: Unalakleet, Alaska
Error: 234 & City: Valdez, Alaska
Error: 235 & City: Valentine, Nebraska
Error: 236 & City: Vero Beach, Florida
Error: 237 & City: Victoria, Texas
Error: 238 & City: Waco, Texas
Error: 239 & City: Walla Walla, Washington
Error: 240 & City: Washington Dulles AP, District of Columbia
Error: 241 & City: Washington National AP, District of Columbia
Error: 242 & City: Waterloo, Iowa
Error: 243 & City: West Palm Beach, Florida
Error: 244 & City: Wichita Falls, Texas
Error: 245 & City: Wichita, Kansas
Error: 246 & City: Williamsport, Pennsylvania
Error: 247 & City: Williston, North Dakota
Error: 248 & City: Wilmington, Delaware
Error: 249 & City: Wilmington, North Carolina
Error: 250 & City: Winnemucca, Nevada
Error: 251 & City: Winslow, Arizona
Error: 252 & City: Worcester, Massachusetts
Error: 253 & City: Yakima, Washington
Error: 254 & City: Yakutat, Alaska
Error: 255 & City: Youngstown, Ohio
Error: 256 & City: Yuma, Arizona
Error: 257 & City: Birmingham, Alabama
Error: 258 & City: St. Paul, Minnesota
Error: 259 & City: Cairo, Illinois
Error: 260 & City: JFK Int'l AP, New York
Error: 261 & City: Block Is., Rhode Island
Error: 262 & City: Laguardia AP, New York

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 107,
 108,
 111,
 112,
 113,
 117,
 120,
 121,
 124,
 125,
 126,
 127,
 130,
 131,
 134,
 135,
 136,
 139,
 140,
 141,
 144,
 145,
 146,
 149,
 150,
 151,
 154,
 155,
 158,
 159,
 160,
 163,
 164,
 167,
 168,
 169,
 172,
 173,
 174,
 177,
 178,
 181,
 182,
 183,
 186,
 187,
 188,
 193,
 194,
 197,
 198,
 199,
 202,
 203,
 208,
 211,
 212,
 213,
 216,
 217,
 218,
 221,
 222,
 223,
 226,
 227,
 230,
 231,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262]

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('table-7-1-6-solarabs.csv')
df

   Surface_Color                  Shade   New  Average  Aged
0          White                   None  0.17     0.25  0.34
1       Aluminum               Specular  0.39     0.44  0.49
2       Aluminum                Diffuse  0.60     0.64  0.68
3    Beige/Cream                   None  0.35     0.42  0.49
4          Black                   None  0.97     0.97  0.97
5          Brown                   None  0.58     0.62  0.67
6           Gray                  Light  0.54     0.58  0.63
7           Gray                 Medium  0.68     0.71  0.74
8          Green                   Dark  0.89     0.90  0.91
9            Red                 Primer  0.89     0.90  0.91
10          Rust         Red Iron Oxide  0.38     0.44  0.50
11           Tan                   None  0.43     0.49  0.55
12      Aluminum  Mill Finish/Unpainted  0.10     0.12  0.15

In [8]:
with open('input_chem_list.csv', 'w') as f:
    for item in my_list:
        f.write("%s\n" % item)

['None',
 'Dark',
 'Mill Finish/Unpainted',
 'Red Iron Oxide',
 'Specular',
 'Primer',
 'Medium',
 'Light',
 'Diffuse']

In [24]:
df = pd.read_csv('met_db.csv')

In [25]:
met_list = df['CTYST'].tolist()

In [26]:
with open('input_met_list.txt', 'w') as f:
    for each in met_list:
        f.write("'" + str(each) + "'" + "," + '\n')